// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

const deleteTelegramBot = `-- name: DeleteTelegramBot :exec
DELETE FROM telegram_bots
WHERE bot_username = ?
`

func (q *Queries) DeleteTelegramBot(ctx context.Context, botUsername string) error {
	_, err := q.exec(ctx, q.deleteTelegramBotStmt, deleteTelegramBot, botUsername)
	return err
}

const getTelegramBotByUsername = `-- name: GetTelegramBotByUsername :one
SELECT bot_username, token, instance_id, chat_id, last_heartbeat_at, last_used_at, created_at FROM telegram_bots
WHERE bot_username = ? LIMIT 1
`

func (q *Queries) GetTelegramBotByUsername(ctx context.Context, botUsername string) (TelegramBot, error) {
	row := q.queryRow(ctx, q.getTelegramBotByUsernameStmt, getTelegramBotByUsername, botUsername)
	var i TelegramBot
	err := row.Scan(
		&i.BotUsername,
		&i.Token,
		&i.InstanceID,
		&i.ChatID,
		&i.LastHeartbeatAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTelegramBots = `-- name: ListTelegramBots :many
SELECT bot_username, token, instance_id, chat_id, last_heartbeat_at, last_used_at, created_at FROM telegram_bots
ORDER BY last_used_at DESC
`

func (q *Queries) ListTelegramBots(ctx context.Context) ([]TelegramBot, error) {
	rows, err := q.query(ctx, q.listTelegramBotsStmt, listTelegramBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelegramBot
	for rows.Next() {
		var i TelegramBot
		if err := rows.Scan(
			&i.BotUsername,
			&i.Token,
			&i.InstanceID,
			&i.ChatID,
			&i.LastHeartbeatAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTelegramBot = `-- name: SaveTelegramBot :exec
INSERT INTO telegram_bots (bot_username, token, instance_id, chat_id, last_heartbeat_at, last_used_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(bot_username) DO UPDATE SET
    token = excluded.token,
    instance_id = excluded.instance_id,
    chat_id = excluded.chat_id,
    last_heartbeat_at = excluded.last_heartbeat_at,
    last_used_at = excluded.last_used_at
`

type SaveTelegramBotParams struct {
	BotUsername    string `json:"bot_username"`
	Token          string `json:"token"`
	InstanceID     string `json:"instance_id"`
	ChatID         int64  `json:"chat_id"`
	LastHeartbeatAt int64 `json:"last_heartbeat_at"`
	LastUsedAt     int64  `json:"last_used_at"`
	CreatedAt      int64  `json:"created_at"`
}

func (q *Queries) SaveTelegramBot(ctx context.Context, arg SaveTelegramBotParams) error {
	_, err := q.exec(ctx, q.saveTelegramBotStmt, saveTelegramBot,
		arg.BotUsername,
		arg.Token,
		arg.InstanceID,
		arg.ChatID,
		arg.LastHeartbeatAt,
		arg.LastUsedAt,
		arg.CreatedAt,
	)
	return err
}

const updateTelegramBotHeartbeat = `-- name: UpdateTelegramBotHeartbeat :exec
UPDATE telegram_bots
SET last_heartbeat_at = ?,
    instance_id = ?
WHERE bot_username = ?
`

type UpdateTelegramBotHeartbeatParams struct {
	LastHeartbeatAt int64  `json:"last_heartbeat_at"`
	InstanceID      string `json:"instance_id"`
	BotUsername     string `json:"bot_username"`
}

func (q *Queries) UpdateTelegramBotHeartbeat(ctx context.Context, arg UpdateTelegramBotHeartbeatParams) error {
	_, err := q.exec(ctx, q.updateTelegramBotHeartbeatStmt, updateTelegramBotHeartbeat,
		arg.LastHeartbeatAt,
		arg.InstanceID,
		arg.BotUsername,
	)
	return err
}
